general:
  verbose: true
  productiveBranch: 'master-qa'
  buildTool: 'npm'
  gitHttpsCredentialsId: 'GitHub-emobility-ci-build'
  githubTokenCredentialsId: 'GitHub-token-emobility-ci-build'

stages:

  Central Build:
    executeSonarScan: false
    sonarExecuteScan: true

  IPScan and PPMS:
    whitesourceProductName: 'SHC - SAP E-MOBILITY BACKEND 1.0'
    whitesourceProjectNames: ['ev-server - 1'] # needed for automation of mapping requests
    whitesourceProductVersion: '1'
    whitesourceProductToken: '1bc6180baace4de497ac4fcf27264aad435caf91baf648bab8171559467f4f49'
    whitesourceUserTokenCredentialsId: 'whitesourceUserTokenEmobility'
    executeWhitesourceScan: true
    sapCheckPPMSCompliance: true
    buildVersion: '{{.Major}}.{{.Minor}}'
    
  Additional Unit Tests:
    karmaExecuteTests: false

#  Acceptance:
#    cloudFoundryDeploy:
#      cloudFoundry/org: SAP_IT_Cloud_sapitcft
#      cloudFoundry/space: e-mobility
#      cloudFoundry/credentialsId: scp-i030367-access
      
    
  Security:
    executeCheckmarxScan: true
    checkmarxExecuteScan: false
    executeWhitesourceScan: false

  Release:
    cloudFoundry/org: SAP_IT_Cloud_sapitcft
    cloudFoundry/space: e-mobility
    cloudFoundry/credentialsId: scp-i030367-access

steps:

  sonarExecuteScan:
    instance: 'SAP SonarQube Enterprise'

  executeWhitesourceScan:
    scanType: npm
   
  executeCheckmarxScan:
  #checkmarxExecuteScan:
    checkmarxProject: 'ev-server'
    #projectName: 'ev-server'
    #checkmarxGroupId: '29091a00-0dbc-4d06-b78b-32ab0ef54cdc'
    checkmarxGroupId: 'f8bb43bd-9a38-4e6a-a932-6a8159817e41'
    preset: 100131 #SAP_Default_Typescript
    checkmarxCredentialsId: 'checkmarx-access'
    filterPattern: '!**/node_modules/**, !**/coverage/**, !**/coverage-tmp/**, !**/.xmake/**, !**/tests/**, !**/jest.config.js, !**/*_test.go, !**/vendor/**/*.go, **/*.html, **/*.xml, **/*.go, **/*.py, **/*.js, **/*.scala, **/*.ts, **/*.tsx'
      
  sapCheckPPMSCompliance:
    ppmsID: '73554900100200014452'
    ppmsCredentialsId: 'ppms-i030367-access'
    ppmsBuildVersionCreation: true
    ppmsChangeRequestUpload: true
