name: Unit Tests CI

on:
  push:
    branches:
      - master
      - master-qa
  pull_request:
    branches:
      - master-qa

jobs:
  unit-tests-submodules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.4]
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.ACTION_ACCESS_SUB_MODULES_PRIVATE_REPOS }}
        submodules: true
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: rs0
    - name: Initialize DB
      run: |
        mongo docker/initdb/000_createMongoUsers.js
        mongo docker/initdb/002_createSuperAdmin.js
    - name: Install NodeJs
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NodeJs Packages
      run: npm ci
    - name: Build production sources
      run: |
        cp src/assets/configs-ci/config.json src/assets
        npm run build:prod
    - name: Start Server in Prod mode
      run: |
        npm run start:prod
    - name: Create Unit Test context
      run: |
        if [ ! -d test/config ]; then mkdir -p test/config; fi
        cp src/assets/configs-ci/local.json test/config
        npm run mochatest:createContext
    - name: Run Unit Test
      run: npm run mochatest

